name: campus_buddy
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  firebase_database: ^10.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # ✅ Add this line

flutter:
  uses-material-design: true

  assets:
    - assets/images/dropr.png

flutter_icons:   # ✅ Add this block
  android: true
  ios: false
  image_path: "assets/images/appicon.png"
